- name: sources.listの更新
  template: src=templates/sources.list dest=/etc/apt/sources.list #mode=0644
- name: podmanのapt-key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{version}}/{{os}}/Release.key
    state: present
- name: cri-o runcのapt-key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{os}}/Release.key
    state: present
- name: podmanの追加
  apt_repository: 
    repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{os}}/ /"
    state: present
    filename: devel:kubic:libcontainers:stable.list
- name: cri-o runcの追加
  apt_repository: 
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{version}}/{{os}}/ /
    state: present
    filename: devel:kubic:libcontainers:stable:cri-o:{{version}}.list
- name: libseccomp2のインストール
  apt:
    name: libseccomp2
    state: latest
    default_release: buster-backports
    update_cache: yes
- name: cri-o cri-o runc cri-toolsのインストール
  apt:
    name:
      - cri-o
      - cri-o-runc
      - cri-tools
    state: latest
    update_cache: yes
# - name: cri-oのインストール
#   apt:
#     name: cri-o-runc
#     state: latest
#     update_cache: yes
# - name: cri-toolsのインストール
#   apt:
#     name: cri-tools
#     state: latest
#     update_cache: yes
- name: crio自動起動登録
  service:
    name: crio
    enabled: yes
    # state: started
# - name: Add the overlay module
#   community.general.modprobe:
#     name: overlay
#     state: present
# - name: Add the br_netfilter module
#   community.general.modprobe:
#     name: br_netfilter
#     state: present
# - name: copy crio.conf
#   template: src=templates/crio.conf dest=/etc/crio/crio.conf #mode=0644
- name: モジュール登録
  template: src=templates/k8s.conf dest=/etc/modules-load.d/k8s.conf