- name: read cmdline.txt
  shell: cat /boot/cmdline.txt
  register: cmdline
- name: cmdline.txt renew
  shell: echo "{{cmdline.stdout_lines[0]}} cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" > /boot/cmdline.txt
  when: "'cgroup_enable' not in cmdline.stdout_lines[0]"
