- name: IPフォワード登録
  template: src=templates/k8s_ip.conf dest=/etc/sysctl.d/k8s.conf
# - reboot:
- name: kubernetesのapt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: kubernetesの追加
  apt_repository: 
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
- name: kubeadmのインストール
  apt:
    name: kubeadm
    state: latest
    update_cache: true
    cache_valid_time: 3600
- name: kubeletのインストール
  apt:
    name: kubelet
    state: latest
    update_cache: true
    cache_valid_time: 3600
- name: kubectlのインストール
  apt:
    name: kubectl
    state: latest
    update_cache: true
    cache_valid_time: 3600
- name: kubeletのcri-o設定
  template: src=templates/kubelet dest=/etc/default/kubelet
# sudo dphys-swapfile swapoff
# sudo systemctl stop dphys-swapfile
# sudo systemctl disable dphys-swapfile
- name: cmdline COPY
  template: src=templates/cmdline.txt dest=/boot/cmdline.txt
- name: SWAP OFF
  # command: swapoff -a
  command: dphys-swapfile swapoff
- name: SWAP Service off
  service:
    name: dphys-swapfile
    enabled: no
    state: stopped
# - name: SWAP OFF fstab
#   command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab