- name: IPフォワード登録
  template: src=templates/k8s_ip.conf dest=/etc/sysctl.d/k8s.conf
# - reboot:
- name: kubernetesのapt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: kubernetesの追加
  apt_repository: 
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
- name: kubeコマンドインストール
  apt:
    name:
      - kubeadm=1.21.3-00
      - kubelet=1.21.3-00
      - kubectl=1.21.3-00
# - name: kubeコマンドインストール
#   apt:
#     name:
#       - kubeadm
#       - kubelet
#       - kubectl
#     state: latest
#     update_cache: true
#     cache_valid_time: 3600
# - name: kubeadmのインストール
#   apt:
#     name: kubeadm=1.21.3-00
#     state: latest
#     update_cache: true
#     cache_valid_time: 3600
# - name: kubeletのインストール
#   apt:
#     name: kubelet=1.21.3-00
#     state: latest
#     update_cache: true
#     cache_valid_time: 3600
# - name: kubectlのインストール
#   apt:
#     name: kubectl=1.21.3-00
#     state: latest
#     update_cache: true
#     cache_valid_time: 3600
- name: kubeletのcri-o設定
  template: src=templates/kubelet dest=/etc/default/kubelet
# sudo dphys-swapfile swapoff
# sudo systemctl stop dphys-swapfile
# sudo systemctl disable dphys-swapfile
# - name: cmdline COPY
#   template: src=templates/cmdline.txt dest=/boot/cmdline.txt
- name: read cmdline.txt
  shell: cat /boot/cmdline.txt
  register: cmdline
- name: cmdline.txt renew
  shell: echo "{{cmdline.stdout_lines[0]}} cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1" > /boot/cmdline.txt
  when: "'cgroup_enable' not in cmdline.stdout_lines[0]"
- name: SWAP OFF
  # command: swapoff -a
  command: dphys-swapfile swapoff
- name: SWAP Service off
  service:
    name: dphys-swapfile
    enabled: no
    state: stopped
# - name: SWAP OFF fstab
#   command: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab